### ISSUE TITLE
Expert Systems Research

### ISSUE THREAD

**Issue by grabl** [graknlabs/kglib#10]
_This issue was originally posted by @jmsfltchr  on 2018-09-14 12:42_.

Why:
Expert Systems are critical for a variety of domains, including chatbots, and medical diagnostics (for their transparency over ML systems)
How:
Research and disseminate how to build a general ES framework for Grakn to demonstrate Grakn's usefulness in this domain.

**Comment by jmsfltchr** [comment]
Closing as not happening in the very near future, focussing more effort on KGCNs.
