### ISSUE TITLE
Cannot install kglib - no matching distribution found for tensorflow

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/kglib#34]
I can't get to install grakn-kglib. After I run "pip3 install grakn-kglib" (inside a new venv), I receive this error: 

`Could not find a version that satisfies the requirement tensorflow==1.11.0 (from grakn-kglib) (from versions: ) No matching distribution found for tensorflow==1.11.0 (from grakn-kglib)
`

I'm running python 3.7.1.

**Comment by jmsfltchr** [comment]
It seems TensorFlow [doesn't work with Python  #3.7+](https://github.com/tensorflow/tensorflow/issues/17022) yet, so it isn't available via pip for that version. Try using a flavour of Python 3.6 instead, that should work. Thanks for raising this!
